openapi: 3.0.0
info:
  title: PDF Report API
  version: 1.0.0
  description: |
    Specification for the dedicated PDF Report endpoint.
    This endpoint aggregates all client data, calculations, and AI analysis into a structure optimized for visualization.

paths:
  /pfp/reports/{clientId}:
    get:
      summary: Get Full Client Report Data
      description: |
        Returns a complete dataset for generating the client's financial plan PDF.
        Includes current assets, calculated goals, and specific metrics for charts (Waterfall, Portfolio).
      parameters:
        - name: clientId
          in: path
          required: true
          schema:
            type: integer
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful report data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ReportResponse:
      type: object
      properties:
        client_profile:
          type: object
          properties:
            id: { type: integer }
            full_name: { type: string, example: "Иванов Иван Иванович" }
            age: { type: integer }
            email: { type: string }
        
        current_situation:
          description: Data for the "Current Financial Health" section
          type: object
          properties:
            assets_total: { type: number, description: "Total value of current assets" }
            liabilities_total: { type: number, description: "Total debts" }
            net_worth: { type: number, description: "Assets - Liabilities" }
            assets_breakdown:
              type: array
              items:
                type: object
                properties:
                  name: { type: string }
                  value: { type: number }

        overall_plan:
          description: Aggregated metrics for the entire plan (all goals combined)
          type: object
          properties:
            chart_waterfall:
              description: >
                Data for the "Investment vs Result" bar/waterfall chart.
                Shows where the money comes from.
              type: object
              properties:
                invested_by_client:
                  type: number
                  description: "Total nominal amount the client will pay (Initial + Monthly * Months)"
                state_support_nominal:
                  type: number
                  description: "Total free money from State (Tax Deductions + Cofinancing)"
                investment_income:
                  type: number
                  description: "Pure market gain (Compound interest on both Client's and State's money)"
                total_projected:
                  type: number
                  description: "Final Sum (Invested + State + Income). This is the height of the final bar."
            
            consolidated_portfolio:
              description: Summary of all recommended instruments across all goals
              type: object
              properties:
                assets_allocation:
                  type: array
                  description: "For Pie Chart (By Asset Class/Instrument)"
                  items:
                    type: object
                    properties:
                      name: { type: string }
                      share: { type: number, description: "Percentage (0-100)" }
                      amount: { type: number }
                      yield: { type: number }

        ai_executive_summary:
          type: string
          description: "Markdown-formatted text generated by AI. Contains 3 paragraphs: Praise, Efficiency Analysis, Recommendation."
          example: |
            Отличное начало! Ваш план охватывает все ключевые цели...
            
            Обратите внимание: государство добавит к вашим вложениям 1.5 млн руб...
            
            Рекомендуем настроить автопополнение, чтобы не пропускать взносы.

        goals_detailed:
          type: array
          description: "List of calculated goals with their specific summaries"
          items:
            type: object
            properties:
              goal_type: { type: string, example: "PENSION" }
              summary:
                type: object
                additionalProperties: true
                description: "Goal-specific metrics (e.g. target_amount, monthly_replenishment, pension_gap_future)"
